### ISSUE TITLE
Evaluation: Historique des manifestations

### ISSUE THREAD

**Issue by XCarrel** [Dardanboy/FestiAccess#1]
La fonctionnalité à réaliser comporte deux volets:

1. Pouvoir sélectionner (checkboxes) des manifestations, cliquer 'Potes' et voir la liste de tous les amis que j'ai vu dans les manifestations sélectionnées
2. Pouvoir voir la liste des manifestations dans lesquelles j'ai rencontré un ami choisi

**Comment by Dardanboy** [comment]
Après en avoir discuté avec vous, il se trouve que la base de données ne contient pas de liste de manifestations. Je dois donc simuler les données de l'API sans modifier celle-ci.

Les choses à faire sont les suivantes:

- Simuler les données du nouvel api en local. Pour cela une classe **SimulateNewApiOffline** s'occupera de renvoyer les données en json formattées selon le fonctionnement du nouvel API. Ces données seront stockées dans le cache local. Le mode offline devra donc être utilisé pour s'assurer que seules ces données seront utilisées.
- Pouvoir afficher une liste de festivaux lorsqu'on est sur la page d'accueil. Par exemple: Paléo, Aventiclap, Montreux festival Jazz
- Le programme de la soirée pour le festival sera pour tous le même étant donné que cela n'était pas prévu à la base.
- On pourra voir dans notre liste d'amis qui est présent dans quel festival actuellement. En cliquant dessus on aura la liste des tous les festivals auxquels il a participé.

**Comment by Dardanboy** [comment]
Après avoir cherché il se trouve que c'est une perte de temps de vouloir simuler la réponse d'une connexion.
En effet, la réponse à un HttpClient.get() est spécifique et retourne des headers etc..

L'idée est la suivante: 

- On se connecte d'abord à l'application avec une connexion à l'API activée (mode online)
- On se connecte normalement comme d'habitude ("Se connecter" -> "Connect avec Dardan (debug)"
- Il faudra ensuite se rendre dans "Contacts" en bas et appuyer sur le bouton ":" de l'utilisateur "Robert de Niro".
- Cela permettra de mettre ces données dans le cache ionic (avec la key: HttpRequestCacheManager)
Il faudra ensuite aller dans "Paramètres" et activer le mode "Hors-ligne" pour que les données soient récupérées dans le cache.
- Il faudra appuyer sur le bouton "Seed nouvel api" pour que les réponses dans le storage soient modifiées avec les nouvelles données de l'API
- Toujours dans les paramètres, cliquer sur "Déconnexion"
- Recommencer l'étapes de connexion.

Il vous sera maintenant possible de travailler avec les données simulées de l'API.

**Comment by Dardanboy** [comment]
Fini le projet tout juste selon ce que nous avions discuté. En effet, j'étais parti du principe que l'application était faîte pour un seul festival (par exemple Paléo) en me basant ce qui était marqué dans **Projet.xlsx**:
1. L'app permet de s'inscrire au système -> j'envoie mon nom + empreinte
2. L'app permet de créer des liens d'amitié -> on envoie ensemble deux empreintes de personnes connues
3. L'app enregistre l'entrée ou la sortie: envoi de l'empreinte seule. L'app nous dit lesquels de nos amis sont encore 'dedans'

Le demande que vous m'avez faîte ne s'est pas basée là-dessus. En découvrant cela, je vous en ai parlé et on s'est mis d'accord sur ce qu'il fallait faire:
- Voir les festivals à l'entrée de l'application (Liste de boutons)
- Quand on appuie sur un bouton on voit le programme du festival (statique)
- Quand on clique sur un utilisateur, on peut voir la liste des festivals où il était et dans lequel il est présent actuellement

Cela touchait l'API (backend), je suis donc parti de quelque chose inexistant à la base et j'ai dû réfléchir quels pouvaient être les données retournées de l'API selon ce que vous m'avez demandé.
Il a fallu que je touche à l'API en la simulant.
J'ai simulé et override les données retournées par l'API de base et cela m'a pris énormément de temps
A ~11h40 seulement, j'ai fini le override les données dans le storage ionic et j'ai pu commencer à travailler sur l'utilisation de ces données.


---
## Autoévaluation
### Ionic
J'ai accompli 6/7 des tâches obligatoires sur eva.mycpnv.ch (tout sauf le composant natif) et j'ai faîte une tâche facultative (écriture dans l'API). Cela fait donc 7/7 tâches accomplies.

###  Bonnes pratiques professionnelles 
Dès le départ j'ai utilisé des bonnes pratiques professionnelles en utilisant le principe DRY ainsi qu'en structurant mon code comme il se doit et en utilisant tout ce qu'on avait  appris jusque-là.

Pour la note d'aujourd'hui, je me donnerais la note de **4.5**
Pour la **note globale je me donnerai 5.25, soit 5.5**.
